on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies.
        run: |
          apt install -y gobject-introspection
        shell: bash
      - uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
        with:
          version: scm
          dependencies: |
            dbus_proxy
